### ISSUE TITLE
fix `go back` character (see screenshot)

### ISSUE THREAD

**Issue by grandicrypto** [RoseOnAurora/rose-frontend#63]
![Screenshot from 2021-11-11 21-23-25](https://user-images.githubusercontent.com/92389129/141398055-4288c66d-17ac-45ac-aa4d-69e39d2d80e8.png)

**Comment by timechamber** [comment]
which browser are you using?

**Comment by grandicrypto** [comment]
chrome and firefox, guess my os doesn't have a default font that supports this arrow, maybe we replace ⭠ with `<CgArrowLeft />` from react icons
